# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ debug ]

jobs:

  build-images:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: marble
          password: ${{ secrets.DRC_GITHUB_REGISTRY }}

      - name: Build
        run: make build
